### ISSUE TITLE
List of unimplemented features / Todo list.

### ISSUE THREAD

**Issue by DelxHQ** [strdstnet/Stardust#6]
### Blocks

- [x] Actually implement blocks
- [ ] Implement correct block break times
- [x] Use correct particles when breaking a block
  - [ ] Blocks sometimes use the wrong particle and sound when breaking them

### Packets

- [x] InventoryTransaction

### Gameplay

- [x] Player damage 
- [ ] Hunger

### Misc

- [x] Work out why sending text formats causes game to disconnect immediately with violation
